CareSheep/CareSheep_Android

- .idea/kotlinc.xml
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianStart.kt
- app/src/main/res/layout/fragment_guardian_start.xml
- app/src/main/res/values/strings.xml
> design:보호자 시작 화면 UI구현

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/elder/ElderVoiceMainActivity.kt
- app/src/main/res/layout/activity_elder_voice_main.xml
> feat : STT 되는지 확인

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/elder/ElderWalkActivity.kt
- app/src/main/res/layout/activity_elder_walk.xml
- app/src/main/res/layout/fragment_guardian_set_walk_step.xml
- app/src/main/res/raw/credentials.json
- app/src/main/res/raw/stt.json
만보기 기능 구현 내용
Manifest 권한 관련 내용 추가 예정
> feat: 만보기 기능 구현

- app/src/main/java/com/swu/caresheep/ui/elder/ElderConnectActivity.kt
- app/src/main/res/drawable/ic_close_30.xml
- app/src/main/res/drawable/rectangle_green_transp_40_radius_30.xml
- app/src/main/res/layout/activity_elder_connect.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
> design: 어르신 - 보호자 연결 화면 UI 구현

- app/src/main/res/layout/activity_recycle_main_schedule.xml
- app/src/main/res/layout/layout_recycler_schedule_item.xml
> design : 보호자 - 알람 UI 구현 (UI 일부 수정)

- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
녹음 종료 기능 수정(버튼 누르면 종료되는 것이 아닌 일정 시간 말하지 않으면 자동 종료되어 홈으로 전환)
> feat : 녹음 종료 기능 수정(버튼 누르면 종료되는 것이 아닌 일정 시간 말하지 않으면 자동 종료되어 홈으로 전환)

- app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecordData.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
파이어베이스에 저장된 데이터 불러와서 보호자 화면에 recyclerview로 보여주기 
우선 content 모든 내용 보이도록 했는데, 이후 몇글자만 보이고 뒷 글자들은 ... 으로 뜨도록 변경 예정
> feat : 파이어베이스에 저장된 데이터 불러와서 보호자 화면에 recyclerview로 보여주기

- app/src/main/java/com/swu/caresheep/Voice.kt
- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
어르신이  말씀한 speech를 text로 변환한 내용을 firebase realtimeDB의 Voice 에 쓰기
아직 텍스트 분석은 안해서 danger이나 in_need는 0으로 설정한 상태 => 이후 수정 예정
> feat : 어르신이  말씀한 speech를 text로 변환한 내용을 firebase realtimeDB의 Voice 에 쓰기

- app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
- app/src/main/res/layout/layout_recycler_record_item.xml
speech가 변환된 text 내용이 다 보이는 게 아니라 10글자 이상이면 뒷 문장은 ...으로 보이도록  & RecordData 없애고 녹음 관련 data class는 모두 Voice로 사용
> feat : speech가 변환된 text 내용이 다 보이지 않고 10글자 이상이면 뒷 글자는 ...으로 & RecordData->Voice로  

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
- app/src/main/res/layout/activity_guardian_voice_detail.xml
> feat : 음성 리스트 클릭 시, 해당 세부 내용으로 데이터 넘겨줘서 보여주기 (날짜와 내용만)

- app/src/main/java/com/swu/caresheep/elder/ElderMedicineFirstActivity.kt
- app/src/main/res/layout/activity_elder_medicine_first.xml
> design : 어르신 약 화면 ui 수정

- app/src/main/java/com/swu/caresheep/elder/ElderWalkActivity.kt
- app/src/main/java/com/swu/caresheep/elder/ElderWalkMainActivity.kt
> fix: 만보기 UI오류 수정

- app/src/main/java/com/swu/caresheep/elder/ElderMedicineFirstActivity.kt
yellow, blue ,,, -> 노랑, 파랑,, 한글로 뜨게
> fix : 어르신 약 알림 화면 text 한글

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/ui/elder/alarm/ElderWalkAlarmActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/AlarmReceiverEmergency.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/AlarmServiceEmergency.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/home/GuardianHomeFragment.kt
> fix: 긴급 상황 알람

- app/src/main/java/com/swu/caresheep/ElderMapsActivity.kt
어르신 위치 지속적으로 갱신되도록 수정 
우선 현재는 앱 실행중일 때 위치가 갱신되도록
> test : 어르신 위치 지속 갱신 test

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/data/model/GuardianSchedule.kt
- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianAddScheduleActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianCalendarFragment.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianScheduleDetailActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianScheduleRVAdapter.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/home/GuardianHomeFragment.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/home/GuardianTodayScheduleRVAdapter.kt
- app/src/main/java/com/swu/caresheep/utils/CalendarUtil.kt
#73 
- 보호자 공유 캘린더와 관련된 함수를 CalendarUtil 클래스로 분리하여 재사용 가능한 함수 구조로 리팩토링
> 공유 캘린더 중복 함수 utill화

- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianElderWeekReportFragment.kt
- app/src/main/res/layout/fragment_guardian_elder_week_report.xml
> fix: 보호자 주간 리포트 퍼센테이지 수정

- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/GuardianSetSleepTimeActivity.kt
- app/src/main/res/drawable/baseline_bedtime_24.xml
- app/src/main/res/layout/activity_guardian_set_sleep_time.xml
> feat: 어르신 수면 시작 시간

- app/src/main/java/com/swu/caresheep/data/model/Guardian.kt
- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/calendar/GuardianCalendarFragment.kt
- app/src/main/java/com/swu/caresheep/ui/start/SplashActivity.kt
- app/src/main/java/com/swu/caresheep/utils/CalendarUtil.kt
- app/src/main/java/com/swu/caresheep/utils/GoogleLoginClient.kt
#73 
- 어르신 화면에서 공유 캘린더와 관련된 함수를 CalendarUtil 클래스로 분리하여 재사용 가능한 함수 구조로 리팩토링
> refactor: 어르신 일정 조회 함수를 CalendarUtil로 대체

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/App.kt
- app/src/main/java/com/swu/caresheep/ElderMapsActivity.kt
- app/src/main/java/com/swu/caresheep/GuardianMapsActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianActivity.kt
- app/src/main/java/com/swu/caresheep/utils/GpsForegroundService.kt
- app/src/main/java/com/swu/caresheep/utils/GpsNotificationManager.kt
- app/src/main/java/com/swu/caresheep/utils/LocationUtil.kt
- app/src/main/res/layout/activity_elder_maps.xml
- app/src/main/res/layout/activity_guardian_maps.xml
- app/src/main/res/values/strings.xml
#81 
- 어르신이 지도 화면 진입 시 위치 권한 허용되어 있으면 포그라운드화 (상태 표시줄 알림 표시)
- 어르신의 실시간 위치 정보를 DB에 저장 및 보호자 지도 화면에서 조회
- 위치 권한이 거부되거나 사용자가 포그라운드 서비스 종료 버튼 누르면 포그라운드 종료
> feat: 어르신 위치 추적 시, 포그라운드화 구현

- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/GuardianSetSleepTimeActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/meal/GuardianSetDinnerTimeActivity.kt
> fix: 어르신 루틴 설정 재조정(수면시간 추가)

- app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
- app/src/main/java/com/swu/caresheep/data/model/Guardian.kt
- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
> test : fcm 알람 테스트 

- app/src/main/java/com/swu/caresheep/elder/AlarmReceiverCheckEmergency.kt
> feat: 어르신 긴급 상황 체크 가능 추가

- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
> fix : token 값 할당

- app/build.gradle
- app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
> test : fcm test

- app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
> fix : fcm test

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/ui/guardian/map/GuardianMapsActivity.kt
- app/src/main/res/drawable/shadow.xml
- app/src/main/res/layout/activity_guardian_add_schedule.xml
- app/src/main/res/layout/activity_guardian_connect.xml
- app/src/main/res/layout/activity_guardian_maps.xml
- app/src/main/res/layout/activity_guardian_schedule_detail.xml
- app/src/main/res/layout/activity_sign_up.xml
- app/src/main/res/values/strings.xml
X
- 보호자 지도에 어르신 정보 추가
- 마커 클릭 시, 어르신 정보 표시
> feat: 보호자 지도에 어르신 정보 추가

- app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
> feat : fcm 푸시 알림 비동기로 전송

- app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
- app/src/main/java/com/swu/caresheep/Voice.kt
- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
- app/src/main/res/layout/layout_recycler_record_item.xml
- Voice 테이블 필드 변경(fix)
- fcm 알림 확인 유무(feat)
- 번호 옆에 확인 유무를 위한 빨강 동그라미 추가(design)
확인 유무 관련 필드 int -> boolean
> fix, feat, design : Voice 테이블 필드 변경, fcm 알림 확인 유무

- app/src/main/res/drawable/baseline_lens_24.xml
> design : fcm 알림 유뮤 판단을 위한 이미지

- app/src/main/java/com/swu/caresheep/elder/ElderVoiceSubActivity.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
- app/src/main/java/com/swu/caresheep/recyclerview/RecycleMainRecordActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
- app/src/main/res/layout/activity_guardian_voice_detail.xml
- app/src/main/res/layout/activity_recycle_record_main.xml
- app/src/main/res/layout/layout_recycler_record_item.xml
-녹음 세부 및 목록 화면 UI 변경  
;툴바 추가 
;날짜 포맷('년 월 일 오전/오후 시 분 초' 형태로)
;연결된 어르신 정보 불러와서 녹음 세부 화면 구성
녹음 내용 배경 색상은 추후 변경 예정
> design, feat : 보호자 화면에서 어르신 음성 녹음 관련 UI 작업

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/GuardianSetEmergencyTimeActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/GuardianSetSleepTimeActivity.kt
- app/src/main/res/drawable/baseline_bed_24.xml
- app/src/main/res/drawable/baseline_report_problem_24.xml
- app/src/main/res/layout/activity_guardian_set_emergency_time.xml
- app/src/main/res/layout/activity_guardian_set_sleep_time.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
> fix: 누락된 UI 및 UI 수정

- app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
fcm 푸시 알람 intent 플래그 변경 
intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)를 -> intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK) 로 변경
> fix : fcm 푸시 알림 intent 플래그 변경

- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/GuardianSetEmergencyTimeActivity.kt
> fix: 수면시간 및 긴급상황 알람 계산 실수 수정

- app/src/main/java/com/swu/caresheep/recyclerview/RecordAdapter.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianVoiceDetailActivity.kt
- app/src/main/res/layout/activity_guardian_voice_detail.xml
> design, refactor : ui 수정, voice_id 제거

- app/src/main/java/com/swu/caresheep/MyFirebaseMessagingService.kt
- app/src/main/java/com/swu/caresheep/ui/start/SignUpActivity.kt
- app/src/main/java/com/swu/caresheep/ui/start/StartActivity.kt
X
- 회원가입 시 뒤로 가기하면 그만두기 Dialog가 안 뜨는 버그 수정
- 구글 로그인을 누르면 항상 계정 선택 창이 뜨도록 수정
> fix: 로그인 및 회원가입 관련 Dialog 미표시 버그 수정

- app/src/main/java/com/swu/caresheep/AlarmHandler.kt
- app/src/main/java/com/swu/caresheep/elder/ElderMedicineFirstActivity.kt
먹음 체크시 알람 취소되도록, 
먹지 않음 체크시 알람 5분후 다시 울리도록하는 동작 모듈화
> refactor : 재알람 관련 동작 모듈화

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/elder/AlarmReceiverCheckEmergency.kt
- app/src/main/java/com/swu/caresheep/elder/ElderGetAlarmTimeActivity.kt
- app/src/main/java/com/swu/caresheep/elder/ElderGetMealAlarmActivity.kt
- app/src/main/java/com/swu/caresheep/elder/ElderWalkActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/alarm/ElderBreakfastAlarmActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/alarm/ElderDinnerAlarmActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/alarm/ElderLunchAlarmActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianElderTodayReportFragment.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianElderWeekReportFragment.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/GuardianSetWalkTimeActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/home/GuardianHomeFragment.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/medicine/GuardianSetMedicineColorActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/mypage/GuardianElderRoutineActivity.kt
> fix: user_id 로그인 시 계정으로 받아오는 값으로 수정

- app/src/main/java/com/swu/caresheep/elder/AlarmService.kt
- app/src/main/java/com/swu/caresheep/elder/ElderMedicineFirstActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/alarm/ElderBreakfastAlarmActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/alarm/ElderDinnerAlarmActivity.kt
- app/src/main/java/com/swu/caresheep/ui/elder/alarm/ElderLunchAlarmActivity.kt
> fix: 모든 알람 5분 후 다시 울림 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/GuardianSetEmergencyTimeActivity.kt
- app/src/main/java/com/swu/caresheep/ui/guardian/emergency/GuardianSetSleepTimeActivity.kt
> fix: 수면 시작 시간 및 긴급 상황 추적 시간 설정 오류 수정

- app/src/main/java/com/swu/caresheep/ui/elder/main/ElderActivity.kt
> fix: 긴급 상황 추적 시간 가져오기

- app/build.gradle
- app/src/main/java/com/swu/caresheep/data/api/KakaoImgSearchApi.kt
- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
노인 식사 습관 분석 후 보호자에게 식단 추천하기 위한 kakao image search api로 이미지 불러오기
> feat : kakao image search api로 이미지 불러오기

- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
- app/src/main/res/layout/fragment_guardian_elder_week_report2.xml
> feat: 루틴 일간 및 주간 UI 및 구조 수정2

- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
kakao api 를 이용해서 추천 식단에 대한 이미지 뜨도록
> fix : kakao api 를 이용해서 추천 식단에 대한 이미지 뜨도록 

- app/src/main/res/layout/activity_guardian_elder_meal_recommend.xml
X
- [보호자] 주간 생활 리포트 - 식단 추천 - 추천 로딩 중 표시되는 텍스트 수정
> fix: 식단 추천 로딩 텍스트 수정

- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderMealRecommendActivity.kt
X
- [보호자] 주간 생활 리포트 - 식단 추천 - 응답으로 온 레시피 누락되는 버그 수정
> fix: 식단 추천 레시피 누락 수정

- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
- app/src/main/java/com/swu/caresheep/guardian/report/GuardianEldereReportViewAdapter.kt
- app/src/main/res/drawable/circle_progressbar_1.xml
- app/src/main/res/drawable/circle_progressbar_2.xml
- app/src/main/res/drawable/circle_progressbar_3.xml
- app/src/main/res/drawable/circle_progressbar_4.xml
- app/src/main/res/layout/activity_guardian_elder_report.xml
- app/src/main/res/layout/fragment_guardian_elder_today_report.xml
- app/src/main/res/layout/fragment_guardian_elder_week_report2.xml
- app/src/main/res/values/styles.xml
> fix: 주간, 일간 리포트 UI 추가 수정 및 연결

- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReportDetailActivity.kt
- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReportFragment.kt
X
- [보호자] 주간 생활 리포트 상세내역 - 운동 루틴 수행률 업데이트 버그 수정
(= 테이블명, 컬럼명 불일치로 인한 오류 수정)
> fix: 주간 리포트 상세내역 운동 루틴 수행률 업데이트 버그 수정

- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
- app/src/main/res/drawable/circle_progressbar_4.xml
> fix: UI 누락 수정2

- app/src/main/java/com/swu/caresheep/guardian/report/GuardianElderWeekReport2Fragment.kt
- app/src/main/res/layout/fragment_guardian_elder_week_report2.xml
> fix: UI 계산 해결
